# Generated by Django 5.1.2 on 2025-02-14 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.TextField()),
                ('pet_name', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
                ('adoption_fee', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('dis', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='app.pet_category')),
            ],
        ),
    ]
